[package]
name = "rustation-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "src/wasm_unified.rs"

[features]
default = []
pgxp = []
debugger = []
vulkan = ["ash", "shaderc", "spirv-reflect"]
opengl = ["gl"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
log = "0.4"
wasm-logger = "0.2"
bitflags = "2.4"
arrayvec = "0.7"
lazy_static = "1.4"
# Texture replacement dependencies  
sha2 = "0.10"
image = "0.24"
flate2 = "1.0"
zip = "0.6"

# Database and compatibility dependencies
rusqlite = { version = "0.30", features = ["bundled", "serde_json"], optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
uuid = { version = "1.6", features = ["v4", "serde"], optional = true }
reqwest = { version = "0.11", features = ["json"], optional = true }
tokio = { version = "1", features = ["rt", "macros"], optional = true }

# Shader compilation dependencies
crossbeam-channel = "0.5"
hex = "0.4"
bincode = "1.3"
num_cpus = "1.16"

# Vulkan dependencies
ash = { version = "0.37", optional = true }
shaderc = { version = "0.8", optional = true }
spirv-reflect = { version = "0.2", optional = true }

# OpenGL dependencies
gl = { version = "0.14", optional = true }

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Document",
  "Element",
  "HtmlCanvasElement",
  "HtmlElement",
  "Window",
  "CanvasRenderingContext2d",
  "ImageData",
  "KeyboardEvent",
  "AudioContext",
  "AudioBuffer",
  "AudioBufferSourceNode",
  "AudioDestinationNode",
  "AudioNode",
  "BaseAudioContext",
  "Gamepad",
  "GamepadButton",
]

[features]
default = []
compatibility-db = ["rusqlite", "chrono", "uuid"]
online-sync = ["reqwest", "tokio", "compatibility-db"]

[profile.release]
opt-level = "s"
lto = true

[package.metadata.wasm-pack]
wasm-opt = false